config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :tweets do 
    resources :retweets, only: [:new, :create, :destroy]
	resources :comments, only: [:new, :create, :destroy]
	resources :re_comments, only: [:new, :create, :destroy]
	
	resources :likes, only: [:create, :destroy]
	resources :re_likes, only: [:create, :destroy]
	
	resources :follows, only: [:create, :destroy]
  end
  
  resources :tweet_pages, only: [:index, :destroy, :show ]
  resources :tweet_page_replies, only: [:index]
  resources :following_pages, only: [:index, :show]
  resources :followers_pages, only: [:index, :show] 
  
  
  devise_scope :user do
	root :to => 'devise/sessions#new'
  end

	
  # post '/tweets/:tweet_id/likes/:id/toggle' => 'likes#toggle'
  
  # root 'tweets#index'

  # Example of regular route:
  # get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  # get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :tweet
	belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
  	@comment = Comment.new 
	@retweet_find = Tweet.find(params[:tweet_id])
	# @retweet = Retweet.new 
	# @retweet_find = Tweet.find(params[:tweet_id])
  end

  def create
    #@comment = Retweet.new(retweet_params)
    @comment = Comment.new(comment_params)

    if @comment.save
	  redirect_to tweets_path, notice: 'comment complete!'
    else
	  render :back
    end
  end
   
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
	
    redirect_to tweets_path
  end

  private
	
    def comment_params
      params.require(:comment).permit(:tweet_id, :comment, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<%= stylesheet_link_tag "comments", :media => "all" %>

<div class="container">
	<div class="margin">
		<h1>Reply</h1>

		<label>content: </label>
		<table class="table table-striped table-hover ">
		  <tr>
			  <td><%= @retweet_find.content %></td>
		  </tr>
		</table>

		<%= form_for(@comment, url: tweet_comments_path) do |f| %>
			
			<div class="form-group">
			  <label>Reply: </label>
			  <input class="form-control input-lg" type=<%= f.text_field :comment %>
			</div>
			
			<%= f.hidden_field :tweet_id, :value => params[:tweet_id] %>
			<%= f.hidden_field :username, :value => current_user.username %>
			<%= f.hidden_field :userId, :value => current_user.userId %>
			<%= f.hidden_field :image, :value => current_user.image %>
			<%= f.hidden_field :user_id, :value => current_user.id %>

			<input class="btn btn-info" type="submit" value="reply">

			<%= link_to tweets_path, class: "btn btn-default" do %>
				Back
			<% end %>
		<% end %>
	</div>
</div>