config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :tweets do 
    resources :retweets, only: [:new, :create, :destroy]
	resources :comments, only: [:new, :create, :destroy]
	resources :re_comments, only: [:new, :create, :destroy]
	
	resources :likes, only: [:create, :destroy]
	resources :re_likes, only: [:create, :destroy]
	
	resources :follows, only: [:create, :destroy]
  end
  
  resources :tweet_pages, only: [:index, :destroy, :show ]
  resources :tweet_page_replies, only: [:index]
  resources :following_pages, only: [:index, :show]
  resources :followers_pages, only: [:index, :show] 
  
  
  devise_scope :user do
	root :to => 'devise/sessions#new'
  end

	
  # post '/tweets/:tweet_id/likes/:id/toggle' => 'likes#toggle'
  
  # root 'tweets#index'

  # Example of regular route:
  # get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  # get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
	
	has_many :retweets
	has_many :likes
	has_many :comments, :dependent => :destroy
	has_many :follows

	validates :content, presence: { message: "入力して！"},
	length: { minimum: 2, message: "短い！" }

	
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :authenticate_user!

	  def index
		@tweet = Tweet.new
		@tweets = Tweet.all.order("id DESC") 
		
		# 카운터
		tweet_count = Tweet.where(user_id: current_user.id).count
		retweet_count = Retweet.where(user_id: current_user.id).count
		comment_count = Comment.where(user_id: current_user.id).count
		recomment_count = ReComment.where(user_id: current_user.id).count
		@tweets_count = tweet_count + retweet_count + comment_count + recomment_count

		# 내 트윗, 리트윗
		own_tweets = current_user.tweets
		own_retweets = current_user.retweets
		
		# 나는 팔로우 목록에서 뺀다
		@users = User.where.not( id: current_user.id )
				
		# follow한 사람의 tweet, retweet
		follow_ids = Follow.where(user_id: current_user.id ).pluck(:follow_id)
		tweets = Tweet.where(user_id: follow_ids)
		retweets = Retweet.where(user_id: follow_ids)
		
		tweets_adds = own_tweets + tweets
		retweets_adds = own_retweets + retweets
		
		@tweets_hash = {}
		
		tweets_adds.each do |tweet|
			@tweets_hash.store(tweet.created_at, tweet)
		end
		retweets_adds.each do |retweet|
			@tweets_hash.store(retweet.created_at, retweet)
		end

		@tweets_hash = @tweets_hash.sort_by{|key, val| key}.reverse!
	  end

	  def new
		@tweet = Tweet.new
	  end
	  
	  def create
		@tweet = Tweet.new(tweet_params)
		
		if @tweet.save		
		  redirect_to tweets_path, notice: 'tweet complete!'
		else
		  render 'new'
		end
	  end
	  
	  def destroy
		@tweet = Tweet.find(params[:id])
		@tweet.destroy
		
		redirect_to :back
	  end
	  
	  def update
		@tweet = Tweet.find(params[:id])
		if @tweet.update(tweet_params)
			  redirect_to tweets_path
		else
		  render 'new'
		end
	  end
	 
	  private
	   
	   def tweet_params
		 params[:tweet].permit(:content, :user_id, :image)
	   end
end

app/views/tweets/index.html.erb
<%= stylesheet_link_tag "test", :media => "all" %>
<div class="row">
<div class="container">

<div class="col-md-3" >	
	<div class="modal-header"> 
	<div class="row">
	</div>
	  <div class="col-sm-9">
		<div class="row">
		  <div class="col-xs-8 col-sm-5">
			<img class="modal-img-rounded" alt="img" height="80" width="80" src="<%= current_user.image %>">
		  </div>
		  <div class="col-xs-4 col-sm-7">
			<div class="username">
				<h4><%= current_user.username %></h4>
				<h6>@<%= current_user.userId %></h6>
			</div>	
		  </div>
		</div>
	  </div>
	</div>

	<div class="modal-footer">
		<div class="an">
			<h6><%= link_to "TWEETS", tweet_pages_path %></h6>
			<h4><%= @tweets_count %></h4>
		</div>
		<div class="an">
			<h6><%= link_to "FOLLOWINGS", following_pages_path %></h6>
			<h4><%= Follow.where(user_id: current_user.id).count %></h4>
		</div>
		<div class="an">
			<h6><%= link_to "FOLLOWERS", followers_pages_path %></h6>
			<h4><%= Follow.where(follow_id: current_user.id).count %></h4>
		</div>
	</div>
</div>

<div class="col-md-6">
	<div class="modal-header-center">	
		<table>
			<tr>
				<td width="3%">
					<img alt="img" class="img-rounded" height="32" width="32" src="<%= current_user.image %>">
				</td>
				<td width="60%">
					<%= form_for @tweet do |f| %>
					  <input class="form-control" type=<%= f.text_field :content,:placeholder => "What's happening?" %>
					  <%= f.hidden_field :user_id, :value => current_user.id %>

					  <% if @tweet.errors.any? %>
						<%= @tweet.errors.messages[:content][0] %>
					  <% end %>
					<% end %>
				</td>
			</tr>
		</table>
	</div>

	<div class="modal-footer-center">
		<div class="center-tweet-all"> 
			<% Hash[@tweets_hash].values.each do |tweet| %>
				<% if tweet.kind_of?(Tweet) %>	
					<div class="center-tweet">
						<div class="center-tweet-image">
						   <%= link_to image_tag( tweet.user.image, :size => "40x40", :class => "img-rounded" ), tweet_page_path(tweet.user.id) %>
						</div>
						
						<div class="center-tweet-right">
							<div class="center-tweet-right-username">
								<strong><%= tweet.user.username %></strong>
							</div>	
							<div class="center-tweet-right-userId">
								@<%= tweet.user.userId %>&nbsp・
								<%= tweet.created_at.strftime('%Y/%m/%d %H:%M') %>
							</div>								
							<div class="center-tweet-right-content">
								<div class="font">
									<%= tweet.content %>
								</div>
							</div>
							
							<!-- 리플 -->
							<div class="center-tweet-right-bt">
								<%= link_to image_tag("reply_bt.png", :size => "15x15"), new_tweet_comment_path(tweet.id, @tweet) %>
							</div>	
							<!-- 리트윗 -->
							<div class="center-tweet-right-bt">
								<%= link_to image_tag("retweet_bt.png", :size => "20x20"), new_tweet_retweet_path(tweet.id, @tweet) %>			  
							</div>
							<!-- 라이크 -->
							<div class="center-tweet-right-bt">
								<% if Like.new.likable_for?(current_user, tweet) %>
									<%= link_to image_tag("favorite_bt.png", :size => "15x15"), tweet_like_path(tweet.id, id: tweet.id), :method => :delete %>
								<% else %>
									<%= link_to image_tag("favorite_bt2.png", :size => "15x15"), tweet_likes_path(tweet_id: tweet.id), method: :post %>
								<% end %>
								<%= tweet.likes.count %>
							</div>	
							
							<% if tweet.user_id == current_user.id %>
								<div class="center-tweet-right-delete">
									<%= link_to tweet_path(tweet.id), method: :delete, class: "btn btn-default btn-sm", data: { confirm: "Are you sure?" } do %>
										Delete
									<% end %>
								</div>
							<% else %>
								
							<% end %>
							
						</div>	
					</div>
					
					<!-- 코멘트 -->
					<% tweet.comments.each do |comment| %>
						<div class="center-tweet">
							<div class="center-tweet-image">
								<%= link_to image_tag( comment.user.image, :size => "40x40", :class => "img-rounded" ), tweet_page_path(comment.user.id) %>
							</div>
							
							<div class="center-tweet-right">
								<div class="center-tweet-right-username">
									<strong><%= comment.user.username %></strong>
									@ <%= comment.user.userId %>&nbsp・
									<%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
								</div>
							</div>
							
							<div class="center-tweet-right-content">
								<div class="font">
									<font color="#4374D9"> 
										@<%= comment.tweet.user.userId %>
									</font>	
									&nbsp<%= comment.comment %>
								</div>
							</div>
						
							<% if comment.user_id == current_user.id %>
								<div class="center-tweet-right-delete">
									<%= link_to tweet_comment_path(comment.tweet_id, comment.id), method: :delete, class: "btn btn-default btn-sm", data: { confirm: "Are you sure?" } do %>
										Delete
									<% end %>
								</div>
							<% else %>
								
							<% end %>
						</div>
					<% end %>
					
				<% else %>
				<!-- retweet -->
					<div class="center-tweet">
						<div class="center-retweet-icon">
							<%= image_tag "retweet_icon.png", size: "16x18" %>
							<%= tweet.user.username %> 
							retweeted
						</div>
						
						<div class="center-tweet-image">						   
							<%= link_to image_tag( tweet.tweet.user.image, :size => "40x40", :class => "img-rounded" ), tweet_page_path(tweet.user.id) %>
						</div>
								
						<div class="center-tweet-right">
							<div class="center-tweet-right-username">
								<strong><%= tweet.tweet.user.username %></strong>
							</div>
							
							<div class="center-tweet-right-userId">
								@<%= tweet.tweet.user.userId %>&nbsp・
								<%= tweet.created_at.strftime('%Y/%m/%d %H:%M') %>
							</div>
							
							<div class="center-tweet-right-content">
								<div class="font">
									<%= tweet.content %>
								</div>
							</div>
							
							<!-- 리플 -->
							<div class="center-tweet-right-bt">
								<%= link_to image_tag("reply_bt.png", :size => "15x15"), new_tweet_re_comment_path(tweet.id, @tweet) %>
							</div>
							
							<!-- 리트윗 -->
							<div class="center-tweet-right-bt">
								<%= link_to image_tag("retweet_bt.png", :size => "20x20"), new_tweet_retweet_path(tweet.tweet_id, @tweet) %>			  
							</div>
							
							<!-- 라이크 -->
							<div class="center-tweet-right-bt">
								<% if ReLike.new.likable_for?(current_user, tweet) %>
									<%= link_to image_tag("favorite_bt.png", :size => "15x15"), tweet_re_like_path(tweet.id, id: tweet.tweet.id), :method => :delete %>
								<% else %>
									<%= link_to image_tag("favorite_bt2.png", :size => "15x15"), tweet_re_likes_path(tweet_id: tweet.id), method: :post %>
								<% end %>
								
								<%= tweet.re_likes.count %>
							</div>	
						
							<% if tweet.user_id == current_user.id %>
								<div class="center-retweet-right-delete">
									<%= link_to tweet_retweet_path(tweet.tweet_id, tweet.id), method: :delete, class: "btn btn-default btn-sm", data: { confirm: "Are you sure?" } do %>
									   Delete
									<% end %>
								</div>	
							<% else %>
									
							<% end %>	
						</div>
					</div>
					
					<!-- 코멘트 -->
					<% tweet.re_comments.each do |recomment| %>
						<div class="center-tweet">
							<div class="center-tweet-image">
								<img class="img-rounded" alt="img" height="40" width="40" src="<%= recomment.user.image %>" />
							</div>
							
							<div class="center-tweet-right">
								<div class="center-tweet-right-username">
									<strong><%= recomment.user.username %></strong>
									@<%= recomment.user.userId%>&nbsp
									<%= recomment.created_at.strftime('%Y/%m/%d %H:%M') %>
								</div>
							</div>
							
							<div class="center-tweet-right-content">
								<div class="font">
									<font color="#4374D9"> 
										@<%= recomment.retweet.tweet.user.userId %>
									</font>	
									&nbsp<%= recomment.comment %>
								</div>
							</div>
						
							<% if recomment.user_id == current_user.id %>
								<div class="center-tweet-right-delete">
									<%= link_to tweet_re_comment_path(recomment.retweet_id, recomment.id), method: :delete, class: "btn btn-default btn-sm", data: { confirm: "Are you sure?" } do %>
										Delete
									<% end %>
								</div>
							<% else %>
								
							<% end %>
						</div>
					<% end %>
					
				<% end %>
				
			<% end %>
		</div>
	</div>
</div>

<div class="col-md-3">
	<div class="modal-right">
	
	<h4>Who to follow</h4>
		<% @users.each do |user| %>
			<div class="follow-all">
				<div class="follow-image">	
					<%= link_to image_tag( user.image, :size => "40x40", :class => "img-rounded" ), tweet_page_path(user.id) %>
				</div>
				
				<div class="follow-user">
					<div class="follow-username">
						<%= link_to user.username, tweet_page_path(user.id) %>
					</div>
					<div class="follow-userId">
						@<%= user.userId%>
					</div>
				</div>		
				
				<div class="follow-bt">
					<% if Follow.new.able?(current_user, user) %>		
						<%= link_to 'UnFollow', tweet_follow_path(user.id, id: current_user.id), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure?" } %>
					<% else %>
						<%= link_to 'Follow', tweet_follows_path(tweet_id: user.id), method: :post, class: "btn btn-info btn-sm" %>
					<% end %>
				</div>
			</div>		
		<% end %>
	</div>
</div>

</div>
</div>

app/views/tweets/new.html.erb
<div id="welcome">
<h1>tweet now</h1>

<%= form_for @tweet do |f| %>

<p>
  <%= f.text_field :content %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :image, :value => current_user.image %>
  <%= f.hidden_field :tweet_userId, :value => current_user.userId %>
  <%= f.hidden_field :tweet_username, :value => current_user.username %>

  <% if @tweet.errors.any? %>
  <%= @tweet.errors.messages[:content][0] %>
  <% end %>
</p>

  <input class="btn btn-primary" name="commit" type="submit" value="tweet">  
	<%= link_to tweets_path, class: "btn btn-default" do %>
		Back
	<% end %>
<% end %>

</div>
<!-- 이거 지금 안씀 -->

app/views/tweets/show.html.erb
<div id="welcome">
content:
<br>
<h1><%= @tweet.content %></h1>
<br>


</div>


app/views/tweets/test.html.erb
<h1>TEST!!</h1>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= project.title %>
    </li>
  <% end %>
</ul>