leeTest/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'welcome/index'

  resources :tweets do 
    resources :retweets
  end
 
  resources :tweets do 
    resources :likes
  end
  
  root 'welcome#index'

  # Example of regular route:
  # get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  # get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

leeTest/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :tweet
end

leeTest/app/models/retweet.rb
class Retweet < ActiveRecord::Base

  belongs_to :tweet
 
end

leeTest/app/models/tweet.rb
class Tweet < ActiveRecord::Base

    belongs_to :user
	
	has_many :likes
	
	validates :content, presence: { message: "入力して！"},
	length: { minimum: 2, message: "短い！" }

end

leeTest/app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :tweets

  mount_uploader :image, ImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates_presence_of :image
  validates_integrity_of :image
  validates_processing_of :image
  
  def create
    @user = User.new(user_params)
  end
  
  def user_params
    params.require(:user).permit(:email, :password, :password_cofirmation, :username, :user_id, :image, :remember_me, :image_cache, :remove_image)
  end

end

leeTest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

    protected
      def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :user_id, :email, :password, :password_cofirmation, :remember_me, :image, :image_cache) } 
	    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :user_id, :email, :password, :password_cofirmation, :remember_me, :image, :image_cache) }
	    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :user_id, :email, :password, :password_cofirmation, :remember_me, :image, :image_cache) }
      end
  
end

leeTest/app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def new
	@like = Like.new 
	@like_find = Tweet.find(params[:tweet_id])
  end

  def create
    @like = Like.new(like_params)

	if @like.save
	  redirect_to tweets_path
    else
	  render :action => “new”
	end
  end
  
  private
  
    def like_params
	  params.require(:like).permit(:tweet_id)
	end
end

leeTest/app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  before_action :set_retweet, only: [:show, :update]

  def show
   @retweet = Tweet.find(params[:id])
  end
  
  def new
	@retweet = Retweet.new 
	@retweet_find = Tweet.find(params[:tweet_id])
  end

  def create
    @retweet = Retweet.new(retweet_params)

	if @retweet.save
	  PostMailer.post_mail.deliver
      
	  redirect_to tweets_path
    else
	  render :action => “new”
	end
  end
  
  private
    def set_retweet
      @retweet = Retweet.find(params[:id])
    end
	
    def retweet_params
	  params.require(:retweet).permit(:tweet_id, :content, :user_id, :t_id)
	end
end

leeTest/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
	@retweets = Retweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    @tweet = Tweet.new(tweet_params)
	if @tweet.save
	  redirect_to tweets_path
	else
	  render 'new'
	end
  end
  
  def update
    @tweet = Tweet.find(params[:id])
	if @tweet.update(tweet_params)
      redirect_to tweets_path
	else
	  render 'new'
	end
  end
  
  
  private
   
    def tweet_params
	  params[:tweet].permit(:content, :user_id)
	end
	
	#필터링(project의 title만)을 해주고 
	#create의 project_params로 넘겨준다
end

leeTest/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

leeTest/app/helpers/application_helper.rb
module ApplicationHelper
end

leeTest/app/helpers/likes_helper.rb
module LikesHelper
end

leeTest/app/helpers/projects_helper.rb
module ProjectsHelper
end

leeTest/app/helpers/retweets_helper.rb
module RetweetsHelper
end

leeTest/app/helpers/welcome_helper.rb
module WelcomeHelper
end

leeTest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
</head>
<body>

<header>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">LeeTest</a>
	
	<% if user_signed_in? %>
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
    
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
	   <li>
	     <%= link_to "twitter", tweets_path %> 
		 <span class="sr-only">
		   (current)
		 </span>
	   </li>
       
		<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
		    <img alt="img" height="30" width="30" src="<%= current_user.image %>" />  
			<%= current_user.username %>
			<span class="caret"></span>
		  </a>
          
		  <ul class="dropdown-menu" role="menu">
            <li><a>ID: <%= current_user.id %> | NAME: <%= current_user.username %> | E-mail: <%= current_user.email %></a></li>
			<li>
			  <a><%= link_to "LOGOUT", destroy_user_session_path, method: :delete %></a>
			</li>
			<li>
			  <a><%= link_to "profile_update", edit_user_registration_path %></a>
			</li>
		  </ul>
        </li>
		
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "main", root_path %></li>
      </ul>
    </div>
	
	
	<% else %>
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
            <%= link_to "Login", new_user_session_path %>		  
		    <span class="sr-only">(current)</span>
		</li>
        <li>
		  <%= link_to "Sign up", new_user_registration_path %>
		</li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "main", root_path %></li>
      </ul>
    </div>
	<% end %>
	
	</div>
  </nav>
</header>

<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

leeTest/app/views/likes/new.html.erb
<div id="signUp">
<h1>like?</h1>

<%= form_for(@like, url: tweet_likes_path) do |f| %>
	<%= f.hidden_field :tweet_id, :value => params[:tweet_id] %>
	<br>
	
    <input class="btn btn-primary" type="submit" value="LIKE !">
	<%= link_to :back, class: "btn btn-default" do %>
    Back
    <% end %>
<% end %>

</div>

leeTest/app/views/retweets/new.html.erb
<div id="welcome">
<h1>retweet?</h1>

content: 
<br>
<table class="table table-striped table-hover ">
  <tr class="info">
      <td><%= @retweet_find.content %></td>
  </tr>
</table>

<%= form_for(@retweet, url: tweet_retweets_path) do |f| %>
	<%= f.hidden_field :tweet_id, :value => params[:tweet_id] %>
	<%= f.hidden_field :t_id, :value => @retweet_find.user_id %>
	<%= f.hidden_field :content, :value => @retweet_find.content %>
	<%= f.hidden_field :user_id, :value => current_user.user_id %>
	
	<input class="btn btn-info" type="submit" value="retweet !">
<% end %>
<br>
<%= link_to tweets_path, class: "btn btn-default" do %>
    Back
<% end %>
 </div>
 

leeTest/app/views/retweets/show.html.erb
<h1>retweet?</h1>
(retweets_show_thml)<br>
<br>

##
<br>
tweet_id: <%= @retweet.id %><br>
t_id: <%= @retweet.user_id %><br>  
content: <%= @retweet.content %><br>
user_id:<%= current_user.user_id %><br>
##
	
<%= form_for @retweet, :url => {:action => 'update'} do |f| %>
	<%= f.hidden_field :tweet_id, :value => @retweet.id %>
	<%= f.hidden_field :t_id, :value => @retweet.user_id %>
	<%= f.hidden_field :content, :value => @retweet.content %>
	<%= f.hidden_field :user_id, :value => current_user.user_id %>
	<br>
	<%= f.submit 'YES' %>
<% end %>
<%= link_to "NO", tweets_path %>

leeTest/app/views/tweets/index.html.erb
<div id="welcome">

<h1>twitter!!</h1>

<table class="table table-striped table-hover ">
   <% @tweets.each do |tweet| %>
    <tr class="active">
      <td><%= link_to tweet.content, tweet_path(tweet.id) %></td>
    </tr>
   <% end %>
   
   <% @retweets.each do |retweet| %>
    <tr class="warning">
      <td><%= retweet.content %></td>
    </tr>
   <% end %>
</table>

<%= link_to new_tweet_path, class: "btn btn-primary" do %>
    Tweet
<% end %>

</div>

leeTest/app/views/tweets/new.html.erb
<div id="welcome">
<h1>tweet now</h1>

<%= form_for @tweet do |f| %>

<p>
  <%= f.text_field :content %>
  <%= f.hidden_field :user_id, :value => current_user.user_id %>
  <% if @tweet.errors.any? %>
  <%= @tweet.errors.messages[:content][0] %>
  <% end %>
</p>

  <input class="btn btn-primary" name="commit" type="submit" value="tweet">  
	<%= link_to tweets_path, class: "btn btn-default" do %>
		Back
	<% end %>
<% end %>


</div>

leeTest/app/views/tweets/show.html.erb
<div id="signUp">
content:
<br>
<h1><%= @tweet.content %></h1>

<br>	
<%= link_to new_tweet_like_path(@tweet), class: "btn btn-primary" do %>
    LIKE
	<span class="badge"><%= @tweet.likes.count %></span>
<% end %> 
&nbsp;

<%= link_to new_tweet_retweet_path(@tweet), class: "btn btn-info" do %>
    retweet
<% end %>
&nbsp;

<%= link_to tweets_path, class: "btn btn-default" do %>
    Back
<% end %>
</div>

leeTest/app/views/tweets/test.html.erb
<h1>TEST!!</h1>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= project.title %>
    </li>
  <% end %>
</ul>

leeTest/app/views/welcome/index.html.erb
<div id="welcome">
<h1>Welcome!!</h1>
</div>