config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :tweets do 
    resources :retweets, only: [:new, :create, :destroy]
	resources :comments, only: [:new, :create, :destroy]
	resources :re_comments, only: [:new, :create, :destroy]
	
	resources :likes, only: [:create, :destroy]
	resources :re_likes, only: [:create, :destroy]
	
	resources :follows, only: [:create, :destroy]
  end
  
  resources :tweet_pages, only: [:index, :destroy, :show ]
  resources :tweet_page_replies, only: [:index]
  resources :following_pages, only: [:index, :show]
  resources :followers_pages, only: [:index, :show] 
  
  
  devise_scope :user do
	root :to => 'devise/sessions#new'
  end

	
  # post '/tweets/:tweet_id/likes/:id/toggle' => 'likes#toggle'
  
  # root 'tweets#index'

  # Example of regular route:
  # get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  # get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/tweet_pages_controller.rb
class TweetPagesController < ApplicationController
	before_action :authenticate_user!
	
	def index
			@tweet = Tweet.new
			
			# 팔로우에서 내 아이디 빼기
			@users = User.where.not( id: current_user.id )
			
			# 카운트
			tweet_count = Tweet.where(user_id: current_user.id).count
			retweet_count = Retweet.where(user_id: current_user.id).count
			comment_count = Comment.where(user_id: current_user.id).count
			recomment_count = ReComment.where(user_id: current_user.id).count
			@tweets_count = tweet_count + retweet_count + comment_count + recomment_count

			#tweet_page hash설정
			
			tweets_page = Tweet.where(user_id: current_user.id)
			tweets_page_retweets = Retweet.where(user_id: current_user.id)
			
			@tweets_page_hash = {}
			
			tweets_page.each do |tweet|
				@tweets_page_hash.store(tweet.created_at, tweet)
			end
			tweets_page_retweets.each do |retweet|
				@tweets_page_hash.store(retweet.created_at, retweet)
			end
			
			@tweets_page_hash = @tweets_page_hash.sort_by{|key, val| key}.reverse!
	end
	
	def show
		@user = User.find(params[:id])
		@user_id = Tweet.where(user_id: @user)
		
		# 카운트
		tweet_count = Tweet.where(user_id: params[:id]).count
		retweet_count = Retweet.where(user_id: params[:id]).count
		comment_count = Comment.where(user_id: params[:id]).count
		recomment_count = ReComment.where(user_id: params[:id]).count
		@tweets_count = tweet_count + retweet_count + comment_count + recomment_count
		
		# hash설정
		tweets_page = Tweet.where(user_id: params[:id])
		tweets_page_retweets = Retweet.where(user_id: params[:id])
			
		@tweets_page_hash = {}
			
		tweets_page.each do |tweet|
			@tweets_page_hash.store(tweet.created_at, tweet)
		end
		tweets_page_retweets.each do |retweet|
			@tweets_page_hash.store(retweet.created_at, retweet)
		end
			
		@tweets_page_hash = @tweets_page_hash.sort_by{|key, val| key}.reverse!
		
		# 팔로우에서 내 아이디 빼기
		@users = User.where.not( id: params[:id] )
			
	end
	
	def destroy
		@tweet = Tweet.find(params[:id])
		@tweet.destroy
		
		redirect_to tweet_pages_path
	end
	
	
end

app/helpers/tweet_pages_helper.rb
module TweetPagesHelper
end

app/views/tweet_pages/index.html.erb
<%= stylesheet_link_tag "tweet_pages", :media => "all" %>

<div class="blue">
	<div class="pink">
		<img alt="img" class="image" height="180" width="180" src="<%= current_user.image %>" />
		<h3><%= current_user.username %></h3>
		@<%= current_user.userId %>	
	</div>
</div>

<div class="blue-bottom">
	<div class="blue-buttons">
		<div class="blue-button">
			<%= link_to "TWEETS", tweet_pages_path %>
		
			<div class="blue-count">	
				<div class="count-font">
					<%= @tweets_count %>
				</div>	
			</div>
		</div>
		
		<div class="blue-button">
			<%= link_to "FOLLOWINGS", following_pages_path %>
		
			<div class="blue-count">	
				<div class="count-font">
					<%= Follow.where(user_id: current_user.id).count %>
				</div>
			</div>
		</div>		
		
		<div class="blue-button">		
			<%= link_to "FOLLOWERS", followers_pages_path %>
		
			<div class="blue-count">
				<div class="count-font">
					<%= Follow.where(follow_id: current_user.id).count %>
				</div>
			</div>
		</div>
		
	</div>
</div>		

<div class="col-md-3">	
</div>

<div class="col-md-5">
	<div class="tweet-page-all">
		<div class="link-row">
			<strong><%= link_to "Tweets", tweet_pages_path %></strong>
			<strong><%= link_to "Tweets & Replies", tweet_page_replies_path %></strong>
		</div>
		<% Hash[@tweets_page_hash].values.each do |tweet| %>
			<div class="tweet-page">
				<% if tweet.kind_of?(Tweet) %>	
					<div class="center-tweet">	
						<div class="tweet-page-image">
							<img alt="img" class="img-rounded" height="25" width="25" src="<%= tweet.user.image %>" />
						</div>
						
						<div class="tweet-page-right">
							<div class="tweet-page-username">
								<strong><%= tweet.user.username %></strong>
							</div>
							<div class="tweet-page-userId">
								@<%= tweet.user.userId %>&nbsp・
								<%= tweet.created_at.strftime('%Y/%m/%d %H:%M') %>
							</div>
							<div class="tweet-page-content">
								<div class="font">
									<%= tweet.content %> 
								</div>
							</div>
										
							<!-- 리플 -->
							<div class="tweet-page-bt">
								<%= link_to image_tag("reply_bt.png", :size => "15x15"), new_tweet_comment_path(tweet.id, @tweet) %>
							</div>
							<!-- 리트윗 -->
							<div class="tweet-page-bt">
								<%= link_to image_tag("retweet_bt.png", :size => "20x20"), new_tweet_retweet_path(tweet.id, @tweet) %>			  
							</div>		
							<!-- 라이크 -->							
							<div class="tweet-page-bt">			
								<% if Like.new.likable_for?(current_user, tweet) %>
									<%= link_to image_tag("favorite_bt.png", :size => "15x15"), tweet_like_path(tweet.id, id: tweet.id), :method => :delete %>
								<% else %>
									<%= link_to image_tag("favorite_bt2.png", :size => "15x15"), tweet_likes_path(tweet_id: tweet.id), method: :post %>
								<% end %>
								<%= tweet.likes.count %>
							</div>
							
							<div class="tweet-page-delete-bt">
								<%= link_to tweet_page_path(tweet.id), method: :delete, class: "btn btn-default  btn-sm", data: { confirm: "Are you sure?" } do %>
									Delete
								<% end %>
							</div>
						</div>
					</div>
					
				<% else %>
				<!-- 리트윗-->
					<div class="tweet-page-icon">
						<%= image_tag "retweet_icon.png", size: "15x15" %>
						<%= tweet.user.username %> retweeted
					</div>
					
					<div class="tweet-page-re-image">
						<%= link_to image_tag( tweet.tweet.user.image, :size => "25x25", :class => "img-rounded" ), tweet_page_path(tweet.user.id) %>
					</div>
						
					<div class="tweet-page-right">
						<div class="tweet-page-username">
							<strong><%= tweet.tweet.user.username %></strong>
						</div>
					
						<div class="tweet-page-userId">
							@<%= tweet.tweet.user.userId %>
							<%= tweet.created_at.strftime('%Y/%m/%d %H:%M') %>
						</div>
							
						<div class="tweet-page-content">
							<div class="font">
								<%= tweet.content %>
							</div>
						</div>
							
						<!-- 리플 -->
						<div class="tweet-page-bt">
							<%= link_to image_tag("reply_bt.png", :size => "15x15"), new_tweet_comment_path(tweet.tweet_id, @tweet) %>
						</div>
						
						<!-- 리트윗 -->
						<div class="tweet-page-bt">
							<%= link_to image_tag("retweet_bt.png", :size => "20x20"), tweet_retweet_path(tweet.tweet_id, tweet.id), method: :delete %>			  
						</div>
							
						<!-- 라이크 -->
						<div class="tweet-page-bt">
							<% if ReLike.new.likable_for?(current_user, tweet) %>
								<%= link_to image_tag("favorite_bt.png", :size => "15x15"), tweet_re_like_path(tweet.id, id: tweet.tweet.id), :method => :delete %>
							<% else %>
								<%= link_to image_tag("favorite_bt2.png", :size => "15x15"), tweet_re_likes_path(tweet_id: tweet.id), method: :post %>
							<% end %>
								
							<%= tweet.re_likes.count %>
						</div>
						
						<div class="tweet-page-delete-bt">
							<%= link_to "Delete", tweet_retweet_path(tweet.tweet_id, tweet.id), method: :delete, class: "btn btn-default  btn-sm", data: { confirm: "Are you sure?" } %>
						</div>
					</div>
				<% end %>
			</div>
		<% end %>
	</div>
</div>


<div class="col-md-3">
	<div class="tweet-page-follow-all">
		
		<h4>Who to follow</h4>
	
		<% @users.each do |user| %>
			<div class="follow-all">
				<div class="follow-image">	
					<%= link_to image_tag( user.image, :size => "55x55", :class => "img-rounded" ), tweet_page_path(user.id) %>
				</div>
				<div class="follow-user">
					<div class="follow-username">
						<strong><%= link_to user.username, tweet_page_path(user.id) %></strong>
					</div>
					<div class="follow-userId">	
						@<%= user.userId%>
					</div>
				</div>
				
				<div class="follow-bt">
					<% if Follow.new.able?(current_user, user) %>		
						<%= link_to 'UnFollow', tweet_follow_path(user.id, id: current_user.id), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure?" } %>
					<% else %>
						<%= link_to 'Follow', tweet_follows_path(tweet_id: user.id), method: :post, class: "btn btn-info btn-sm" %>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>	
</div>

app/views/tweet_pages/show.html.erb

<%= stylesheet_link_tag "tweet_pages", :media => "all" %>

<div class="blue">
	<div class="pink">
		<img alt="img" class="image" height="180" width="180" src="<%= @user.image %>" />
		<h3><%= @user.username %></h3>
		@<%= @user.userId %>		
	</div>
</div>

<div class="blue-bottom">
	<div class="blue-buttons">
		<div class="blue-button">
			<%= link_to "TWEETS", tweet_page_path %>
			
			<div class="blue-count">	
				<div class="count-font">
					<%= @tweets_count %>
				</div>	
			</div>
		</div>
		
		<div class="blue-button">
			<%= link_to "FOLLOWINGS", following_page_path %>
			
			<div class="blue-count">	
				<div class="count-font">
					<%= Follow.where(user_id: @user.id).count %>
				</div>
			</div>
		</div>		
			
		<div class="blue-button">		
			<%= link_to "FOLLOWERS", followers_page_path %>
		
			<div class="blue-count">
				<div class="count-font">
					<%= Follow.where(follow_id: @user.id).count %>
				</div>
			</div>
		</div>
	</div>
	
	<div class="follow_bt">
		<% if Follow.new.able?(current_user, @user) %>		
			<%= link_to 'UnFollow', tweet_follow_path(@user.id, id: current_user.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
		<% else %>
			<%= link_to 'Follow', tweet_follows_path(tweet_id: @user.id), method: :post, class: "btn btn-info" %>
		<% end %>
	</div>
</div>	

	
<div class="col-md-3">	
</div>

<div class="col-md-5">
	<div class="tweet-page-all">
		<% Hash[@tweets_page_hash].values.each do |tweet| %>
			<div class="tweet-page">
				<% if tweet.kind_of?(Tweet) %>	
					<div class="center-tweet">	
						<div class="tweet-page-image">
							<img alt="img" class="img-rounded" height="25" width="25" src="<%= tweet.user.image %>" />
						</div>
						
						<div class="tweet-page-right">
							<div class="tweet-page-username">
								<strong><%= tweet.user.username %></strong>
							</div>
							<div class="tweet-page-userId">
								@<%= tweet.user.userId %>&nbsp
								<%= tweet.created_at.strftime('%Y/%m/%d %H:%M') %>
							</div>
							<div class="tweet-page-content">
								<div class="font">
									<%= tweet.content %> 
								</div>
							</div>
									
							<div class="tweet-page-bt">
								<%= link_to image_tag("reply_bt.png", :size => "15x15"), new_tweet_comment_path(tweet.id, @tweet) %>
							</div>
							<div class="tweet-page-bt">
								<%= link_to image_tag("retweet_bt.png", :size => "20x20"), new_tweet_retweet_path(tweet.id, @tweet) %>			  
							</div>								
							<div class="tweet-page-bt">			
								<% if Like.new.likable_for?(current_user, tweet) %>
									<%= link_to image_tag("favorite_bt.png", :size => "15x15"), tweet_like_path(tweet.id, id: tweet.id), :method => :delete %>
								<% else %>
									<%= link_to image_tag("favorite_bt2.png", :size => "15x15"), tweet_likes_path(tweet_id: tweet.id), method: :post %>
								<% end %>
								<%= tweet.likes.count %>
							</div>
							
						</div>
					</div>
					
				<% else %>
					<div class="tweet-page-icon">
						<%= image_tag "retweet_icon.png", size: "15x15" %>
						<%= tweet.user.username %> retweeted
					</div>
					
					<div class="tweet-page-re-image">
						<%= link_to image_tag( tweet.tweet.user.image, :size => "25x25", :class => "img-rounded" ), tweet_page_path(tweet.user.id) %>
					</div>
						
					<div class="tweet-page-right">
						<div class="tweet-page-username">
							<strong><%= tweet.tweet.user.username %></strong>
						</div>
					
						<div class="tweet-page-userId">
							@<%= tweet.tweet.user.userId %>
							<%= tweet.created_at.strftime('%Y/%m/%d %H:%M') %>
						</div>
							
						<div class="tweet-page-content">
							<div class="font">
								<%= tweet.content %>
							</div>
						</div>
							
						<div class="tweet-page-bt">
							<%= link_to image_tag("reply_bt.png", :size => "15x15"), new_tweet_comment_path(tweet.tweet_id, @tweet) %>
						</div>
						
						<div class="tweet-page-bt">
							<%= link_to image_tag("retweet_bt.png", :size => "20x20"), tweet_retweet_path(tweet.tweet_id, tweet.id), method: :delete %>			  
						</div>
							
						<div class="tweet-page-bt">
							<% if ReLike.new.likable_for?(current_user, tweet) %>
								<%= link_to image_tag("favorite_bt.png", :size => "15x15"), tweet_re_like_path(tweet.id, id: tweet.tweet.id), :method => :delete %>
							<% else %>
								<%= link_to image_tag("favorite_bt2.png", :size => "15x15"), tweet_re_likes_path(tweet_id: tweet.id), method: :post %>
							<% end %>
								
							<%= tweet.re_likes.count %>
						</div>	
					</div>
				<% end %>
			</div>
		<% end %>
	</div>
</div>


<div class="col-md-3">
	<div class="tweet-page-follow-all">
		
		<h4>Who to follow</h4>
	
		<% @users.each do |user| %>
			<div class="follow-all">
				<div class="follow-image">	
					<%= link_to image_tag( user.image, :size => "55x55", :class => "img-rounded" ), tweet_page_path(user.id) %>
				</div>
				<div class="follow-user">
					<div class="follow-username">
						<strong><%= link_to user.username, tweet_page_path(user.id) %></strong>
					</div>
					<div class="follow-userId">	
						@<%= user.userId%>
					</div>
				</div>
				
				<div class="follow-bt">
					<% if Follow.new.able?(current_user, user) %>		
						<%= link_to 'UnFollow', tweet_follow_path(user.id, id: current_user.id), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure?" } %>
					<% else %>
						<%= link_to 'Follow', tweet_follows_path(tweet_id: user.id), method: :post, class: "btn btn-info btn-sm" %>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>	
</div>